apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy # done using base 64 encoder username is mongouser
  mongo-password: bW9uZ29wYXNzd29yZA== # done using base 64 encoder password is mongopassword